EXCEPTION DELETE
Exceptions:

- Path not found: <dir>/d3/bad file
CallStack (from HasCallStack):
  throwWithCallStack, called at src/Effects/MonadCallStack.hs:58:24 in monad-callstack-0.1-e615dfec3911c18fa010e1ad03d4acb9d70c3611c1d0a4ac7db26fb06a6ab4e9:Effects.MonadCallStack
  throwWithCallStack, called at src/Effects/MonadCallStack.hs:64:31 in monad-callstack-0.1-e615dfec3911c18fa010e1ad03d4acb9d70c3611c1d0a4ac7db26fb06a6ab4e9:Effects.MonadCallStack
  throwWithCallStack, called at test/functional/Functional/Prelude.hs:118:7 in main:Functional.Prelude
  throwWithCallStack, called at src/SafeRm/Data/PathData.hs:261:14 in safe-rm-0.1-inplace:SafeRm.Data.PathData
  toPathData, called at src/SafeRm.hs:103:15 in safe-rm-0.1-inplace:SafeRm
  delete, called at src/SafeRm/Runner.hs:125:23 in safe-rm-0.1-inplace:SafeRm.Runner
  runCmd, called at test/functional/Functional/Prelude.hs:263:33 in main:Functional.Prelude

LOGS DELETE
[2020-05-31 12:00:00][functional.delete][Debug][src/SafeRm.hs] Trash home: <dir>/d3/.trash
[2020-05-31 12:00:00][functional.delete.deleting][Warn][src/SafeRm.hs] Path not found: <dir>/d3/bad file
CallStack (from HasCallStack):
  throwWithCallStack, called at src/Effects/MonadCallStack.hs:58:24 in monad-callstack-0.1-e615dfec3911c18fa010e1ad03d4acb9d70c3611c1d0a4ac7db26fb06a6ab4e9:Effects.MonadCallStack
  throwWithCallStack, called at src/Effects/MonadCallStack.hs:64:31 in monad-callstack-0.1-e615dfec3911c18fa010e1ad03d4acb9d70c3611c1d0a4ac7db26fb06a6ab4e9:Effects.MonadCallStack
  throwWithCallStack, called at test/functional/Functional/Prelude.hs:118:7 in main:Functional.Prelude
  throwWithCallStack, called at src/SafeRm/Data/PathData.hs:261:14 in safe-rm-0.1-inplace:SafeRm.Data.PathData
  toPathData, called at src/SafeRm.hs:103:15 in safe-rm-0.1-inplace:SafeRm
  delete, called at src/SafeRm/Runner.hs:125:23 in safe-rm-0.1-inplace:SafeRm.Runner
  runCmd, called at test/functional/Functional/Prelude.hs:263:33 in main:Functional.Prelude
[2020-05-31 12:00:00][functional.delete][Info][src/SafeRm.hs] Deleted: 
[2020-05-31 12:00:00][functional][Error][src/SafeRm/Runner.hs] Exceptions:

- Path not found: <dir>/d3/bad file
CallStack (from HasCallStack):
  throwWithCallStack, called at src/Effects/MonadCallStack.hs:58:24 in monad-callstack-0.1-e615dfec3911c18fa010e1ad03d4acb9d70c3611c1d0a4ac7db26fb06a6ab4e9:Effects.MonadCallStack
  throwWithCallStack, called at src/Effects/MonadCallStack.hs:64:31 in monad-callstack-0.1-e615dfec3911c18fa010e1ad03d4acb9d70c3611c1d0a4ac7db26fb06a6ab4e9:Effects.MonadCallStack
  throwWithCallStack, called at test/functional/Functional/Prelude.hs:118:7 in main:Functional.Prelude
  throwWithCallStack, called at src/SafeRm/Data/PathData.hs:261:14 in safe-rm-0.1-inplace:SafeRm.Data.PathData
  toPathData, called at src/SafeRm.hs:103:15 in safe-rm-0.1-inplace:SafeRm
  delete, called at src/SafeRm/Runner.hs:125:23 in safe-rm-0.1-inplace:SafeRm.Runner
  runCmd, called at test/functional/Functional/Prelude.hs:263:33 in main:Functional.Prelude
