EXCEPTION DELETE
Exceptions:

- Path not found: <dir>/d3/bad file

LOGS DELETE
[2020-05-31 12:00:00][functional.delete][Debug] Trash home: <dir>/d3/.trash
[2020-05-31 12:00:00][functional.delete.deleting][Warn] Path not found: <dir>/d3/bad file

CallStack (from HasCallStack):
  getCallStack, called at src/SafeRm/Effects/MonadCallStack.hs:47:20 in <package>:SafeRm.Effects.MonadCallStack
  throwCallStack, called at src/SafeRm/Data/PathData.hs:216:14 in <package>:SafeRm.Data.PathData
  toPathData, called at src/SafeRm.hs:105:15 in <package>:SafeRm
  delete, called at src/SafeRm/Runner.hs:136:23 in <package>:SafeRm.Runner
  runCmd, called at test/functional/Functional/Prelude.hs:242:36 in <package>:Functional.Prelude
[2020-05-31 12:00:00][functional.delete][Info] Deleted: 
[2020-05-31 12:00:00][functional][Error] Exceptions:

- Path not found: <dir>/d3/bad file

CallStack (from HasCallStack):
  getCallStack, called at src/SafeRm/Effects/MonadCallStack.hs:47:20 in <package>:SafeRm.Effects.MonadCallStack
  throwCallStack, called at src/SafeRm/Data/PathData.hs:216:14 in <package>:SafeRm.Data.PathData
  toPathData, called at src/SafeRm.hs:105:15 in <package>:SafeRm
  delete, called at src/SafeRm/Runner.hs:136:23 in <package>:SafeRm.Runner
  runCmd, called at test/functional/Functional/Prelude.hs:242:36 in <package>:Functional.Prelude
