TERMINAL LIST
Type:      File
Name:      f1
Original:  <dir>/r3/f1
Created:   2020-05-31 12:00:00 
Entries:      1
Total Files:  1
Size:         10.00B 


EXCEPTION RESTORE
Encountered exception(s)
- Path not found: bad file


LOGS RESTORE
[2020-05-31 12:00:00][functional.restore][Debug][src/SafeRm.hs:239:4] Trash home: <dir>/r3/.trash
[2020-05-31 12:00:00][functional.restore.readIndex][Debug][src/SafeRm/Data/Index.hs:103:4] Index path: <dir>/r3/.trash/.index.csv
[2020-05-31 12:00:00][functional.restore.readIndex.readIndexWithFold][Debug][src/SafeRm/Data/Index.hs:108:8] Found: MkPathData {pathType = PathTypeFile, fileName = MkPathI {unPathI = "f1"}, originalPath = MkPathI {unPathI = "<dir>/r3/f1"}, created = MkTimestamp {unTimestamp = 2020-05-31 12:00:00}}
[2020-05-31 12:00:00][functional.restore][Info][src/SafeRm.hs:262:4] Restored: 
[2020-05-31 12:00:00][functional][Error][src/SafeRm/Runner.hs:134:8] MkExceptionI (Proxy ExceptionIndex 'SomeExceptions) (MkExceptionI (Proxy ExceptionIndex 'PathNotFound) "bad file" :| [])


